export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";

export const OPEN_CATEGORIES = "OPEN_CATEGORIES";
export const CLOSE_CATEGORIES = "CLOSE_CATEGORIES";

export const OPEN_ACTORS = "OPEN_ACTORS";
export const CLOSE_ACTORS = "CLOSE_ACTORS";

export const OPEN_CATEGORIES_SECTIONS = "OPEN_CATEGORIES_SECTIONS";

export const SET_LIGHT_STATUS = "SET_LIGHT_STATUS";