export const OPEN_MENU = "OPEN_MENU";
export const CLOSE_MENU = "CLOSE_MENU";

export const OPEN_CATEGORIES = "OPEN_CATEGORIES";
export const CLOSE_CATEGORIES = "CLOSE_CATEGORIES";

export const OPEN_DOWNLOAD_BOX = "OPEN_DOWNLOAD_BOX";
export const CLOSE_DOWNLOAD_BOX = "CLOSE_DOWNLOAD_BOX";

export const OPEN_CATEGORIES_SECTIONS = "OPEN_CATEGORIES_SECTIONS";

export const SET_LIGHT_STATUS = "SET_LIGHT_STATUS";